package tv.turbik.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table VIDEO.
 */
public class Video {

    private Long id;
    /** Not-null value. */
    private String lang;
    /** Not-null value. */
    private String quality;
    private int totalLength;

    public Video() {
    }

    public Video(Long id) {
        this.id = id;
    }

    public Video(Long id, String lang, String quality, int totalLength) {
        this.id = id;
        this.lang = lang;
        this.quality = quality;
        this.totalLength = totalLength;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getLang() {
        return lang;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLang(String lang) {
        this.lang = lang;
    }

    /** Not-null value. */
    public String getQuality() {
        return quality;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setQuality(String quality) {
        this.quality = quality;
    }

    public int getTotalLength() {
        return totalLength;
    }

    public void setTotalLength(int totalLength) {
        this.totalLength = totalLength;
    }

}
