package tv.turbik.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EPISODE_VIDEO.
 */
public class EpisodeVideo {

    /** Not-null value. */
    private String alias;
    private int season;
    private int episode;
    /** Not-null value. */
    private String lang;
    /** Not-null value. */
    private String quality;
    private int partStart;
    private int partLength;
    private int totalLength;

    public EpisodeVideo() {
    }

    public EpisodeVideo(String alias, int season, int episode, String lang, String quality, int partStart, int partLength, int totalLength) {
        this.alias = alias;
        this.season = season;
        this.episode = episode;
        this.lang = lang;
        this.quality = quality;
        this.partStart = partStart;
        this.partLength = partLength;
        this.totalLength = totalLength;
    }

    /** Not-null value. */
    public String getAlias() {
        return alias;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAlias(String alias) {
        this.alias = alias;
    }

    public int getSeason() {
        return season;
    }

    public void setSeason(int season) {
        this.season = season;
    }

    public int getEpisode() {
        return episode;
    }

    public void setEpisode(int episode) {
        this.episode = episode;
    }

    /** Not-null value. */
    public String getLang() {
        return lang;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLang(String lang) {
        this.lang = lang;
    }

    /** Not-null value. */
    public String getQuality() {
        return quality;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setQuality(String quality) {
        this.quality = quality;
    }

    public int getPartStart() {
        return partStart;
    }

    public void setPartStart(int partStart) {
        this.partStart = partStart;
    }

    public int getPartLength() {
        return partLength;
    }

    public void setPartLength(int partLength) {
        this.partLength = partLength;
    }

    public int getTotalLength() {
        return totalLength;
    }

    public void setTotalLength(int totalLength) {
        this.totalLength = totalLength;
    }

}
