package tv.turbik.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EPISODE.
 */
public class Episode {

    private String seriesAlias;
    private byte season;
    private byte episode;
    /** Not-null value. */
    private String nameEn;
    private String nameRu;
    private String smallPosterUrl;
    private String hash;
    private String metaData;

    public Episode() {
    }

    public Episode(String seriesAlias, byte season, byte episode, String nameEn, String nameRu, String smallPosterUrl, String hash, String metaData) {
        this.seriesAlias = seriesAlias;
        this.season = season;
        this.episode = episode;
        this.nameEn = nameEn;
        this.nameRu = nameRu;
        this.smallPosterUrl = smallPosterUrl;
        this.hash = hash;
        this.metaData = metaData;
    }

    public String getSeriesAlias() {
        return seriesAlias;
    }

    public void setSeriesAlias(String seriesAlias) {
        this.seriesAlias = seriesAlias;
    }

    public byte getSeason() {
        return season;
    }

    public void setSeason(byte season) {
        this.season = season;
    }

    public byte getEpisode() {
        return episode;
    }

    public void setEpisode(byte episode) {
        this.episode = episode;
    }

    /** Not-null value. */
    public String getNameEn() {
        return nameEn;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    public String getNameRu() {
        return nameRu;
    }

    public void setNameRu(String nameRu) {
        this.nameRu = nameRu;
    }

    public String getSmallPosterUrl() {
        return smallPosterUrl;
    }

    public void setSmallPosterUrl(String smallPosterUrl) {
        this.smallPosterUrl = smallPosterUrl;
    }

    public String getHash() {
        return hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

    public String getMetaData() {
        return metaData;
    }

    public void setMetaData(String metaData) {
        this.metaData = metaData;
    }

}
