package tv.turbik.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table VIDEO_PART.
 */
public class VideoPart {

    private Long id;
    private int start;
    private int length;

    public VideoPart() {
    }

    public VideoPart(Long id) {
        this.id = id;
    }

    public VideoPart(Long id, int start, int length) {
        this.id = id;
        this.start = start;
        this.length = length;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getStart() {
        return start;
    }

    public void setStart(int start) {
        this.start = start;
    }

    public int getLength() {
        return length;
    }

    public void setLength(int length) {
        this.length = length;
    }

}
